### PR TITLE
changed meetup integration to use jsonp direct from api

### PR DESCRIPTION
**Pull request by rodnaph**
/cc @craigmarvelley 

i created a new account on meetup to get an API key for (so if the key does get used for nefarious purposes then not so much worries).

what ya think?

### CODE REVIEW

**Comment by warrenseymour** [comment]
Haven't tested but looks good

**Comment by gavD** [comment]
You haven't defined JSON_CALLBACK anywhere, does it work by magic somehow?

Anyway, I've tested it locally and it's working fine. 1 GOLD TACKLE BOX TO RUDERS

**Comment by rodnaph** [comment]
@gavD FYI JSON_CALLBACK is replaced by Angular - https://docs.angularjs.org/api/ng/service/$http#jsonp

**Comment by gavD** [comment]
OK sossij

On 26 April 2015 at 17:15, Rhodri Pugh <notifications@github.com> wrote:

> @gavD <https://github.com/gavD> FYI JSON_CALLBACK is replaced by Angular
> - https://docs.angularjs.org/api/ng/service/$http#jsonp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unified-diff/unified-diff.github.com/pull/106#issuecomment-96404215>
> .
>



-- 
gavd.co.uk - my site
unifieddiff.co.uk - monthly tech meetup in Cardiff
leanpub.com/dealwithit - my book on attitude for coders
cardiffdevworkshop.com - workshops for programmers

**Comment by craigmarvelley** [comment]
+1, nice one dude!

**Pull request merged**
